### PR TITLE
Subflows

### PR DESCRIPTION
**Pull request by definelicht**
Allow nested dataflow functions.

### CODE REVIEW

**Comment by definelicht** [comment]
@derpda I had an idea on how to simplify subflows by reusing the regular dataflow syntax. Essentially I just threw about the singleton pattern and initialize a local context every time `HLSLIB_DATAFLOW_INIT` is called.

To be quite honest I'm not sure why I didn't do this in the first place!

Do you mind trying this out with your use case and see if it is covered?

**Comment by derpda** [comment]
I can't try it this weekend, but if the test is running it might be ok. Although I should probably explicitly set the pipe depth to 1 in the test.

My worry is that calling `FINALIZE` blocks the thread as far as I understand.
The point of my implementation is that it starts all subthreads and then returns to the main program flow without waiting for them to finish their actual work, but also without destroying the context - thus the need for the condition variable

**Comment by definelicht** [comment]
It blocks the thread, but this thread is itself a dataflow function in the outside context, so you essentially have a nested `Join()` 🤓

Give it a try, I think it should cover your case!

**Comment by derpda** [comment]
I can't check right now, but if it no longer uses the singleton idiom it should indeed be fine as you say!

If it works it sounds like a much simpler solution so that's great!

**Comment by definelicht** [comment]
There's no rush with this, since (obviously) no one else relies on this atm, so if you get a chance to check next week or something I'll just hold out :-)

**Comment by derpda** [comment]
I tested it and it works fine for our use case =)

**Comment by definelicht** [comment]
Excellent, then you can rely on master of the main repo for your project again?

**Comment by derpda** [comment]
Yes, thank you!

**Pull request merged**
